version: '3'
services:
  jupyter:
    image: jupyter/datascience-notebook
    container_name: jupyter_case_1
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    networks:
      - jupyter_network
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres_case_1
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - jupyter_network

networks:
  jupyter_network:

volumes:
  pg_data: