version: '3'
services:
  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: jupyter_case_1
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./scripts:/home/jovyan/scripts
      - ./data:/home/jovyan/data
    environment:
      - JUPYTER_ENABLE_LAB=yes
    networks:
      - jupyter_network
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres_case_1
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db:/db
      - ./scripts/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    environment:
      POSTGRES_DB: case1_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
    networks:
      - jupyter_network

networks:
  jupyter_network:

volumes:
  pg_data: