BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS DIM_FORNECEDOR (
    PK_FORNECEDOR SERIAL NOT NULL,
    CD_FORNECEDOR INTEGER NOT NULL,
    DS_FORNECEDOR VARCHAR(1000) NOT NULL,
   

    CONSTRAINT PK_FORNECEDOR_CONSTRAINT PRIMARY KEY (PK_FORNECEDOR)
);

CREATE TABLE IF NOT EXISTS DEPARA_CENTRO_CUSTOS (
    PK_NORMAL_CENTRO_CUSTOS SERIAL NOT NULL,
    DS_NORMAL_CENTRO_CUSTOS VARCHAR(1000) NOT NULL,
   

    CONSTRAINT PK_NORMAL_CENTRO_CUSTOS_CONSTRAINT PRIMARY KEY (PK_NORMAL_CENTRO_CUSTOS)
);

CREATE TABLE IF NOT EXISTS DIM_CENTRO_CUSTOS (
    PK_CENTRO_CUSTOS SERIAL NOT NULL,
    DS_CENTRO_CUSTOS VARCHAR(1000) NOT NULL,
    -- CD_CENTRO_CUSTOS INTEGER NOT NULL,
    CD_CENTRO_CUSTOS INTEGER,
    SK_NORMAL_CENTRO_CUSTOS INTEGER,
    -- SK_NORMAL_CENTRO_CUSTOS INTEGER NOT NULL,
   

    CONSTRAINT PK_CENTRO_CUSTOS_CONSTRAINT PRIMARY KEY (PK_CENTRO_CUSTOS),
    CONSTRAINT FK_NORMAL_CENTRO_CUSTOS FOREIGN KEY (SK_NORMAL_CENTRO_CUSTOS) REFERENCES DEPARA_CENTRO_CUSTOS (PK_NORMAL_CENTRO_CUSTOS)
);

CREATE TABLE IF NOT EXISTS DIM_UNIDADE (
    PK_UNIDADE INTEGER NOT NULL,
    DS_UNIDADE VARCHAR(1000) NOT NULL,

    CONSTRAINT PK_UNIDADE_CONSTRAINT PRIMARY KEY (PK_UNIDADE)
);

CREATE TABLE IF NOT EXISTS DIM_EMPRESA_EXECUTANTE (
    PK_EMPRESA_EXEC INTEGER NOT NULL,
    DS_EMPRESA_EXEC VARCHAR(1000) NOT NULL,
    PK_UNIDADE INTEGER NOT NULL,

    CONSTRAINT PK_EMPRESA_EXEC_CONSTRAINT PRIMARY KEY (PK_EMPRESA_EXEC),
    CONSTRAINT FK_UNIDADE FOREIGN KEY (PK_UNIDADE) REFERENCES DIM_UNIDADE (PK_UNIDADE)
);

CREATE TABLE IF NOT EXISTS DIM_CONTA_BANCARIA (
    PK_CONTA_BANCARIA SERIAL NOT NULL,
    SK_EMPRESA_EXEC INTEGER NOT NULL,
    CD_CONTA_BANCARIA INTEGER NOT NULL,
    CD_AGENCIA INTEGER NOT NULL,
    DS_CONTA_BANCARIA VARCHAR(1000) NOT NULL,
    CD_BANCO INTEGER NOT NULL,
    SN_ATIVO VARCHAR(1) NOT NULL,
   

    CONSTRAINT PK_CONTA_BANCARIA_CONSTRAINT PRIMARY KEY (PK_CONTA_BANCARIA),
    CONSTRAINT FK_EMPRESA_EXEC FOREIGN KEY (SK_EMPRESA_EXEC) REFERENCES DIM_EMPRESA_EXECUTANTE (PK_EMPRESA_EXEC)
);

CREATE TABLE IF NOT EXISTS FATO_SALDO_INICIAL (
    CD_SALDO_INICIAL INTEGER NOT NULL,
    DT_SALDO_INICIAL DATE NOT NULL,
    VL_SALDO_INICIAL NUMERIC(10,2) NOT NULL,
    SK_CONTA_BANCARIA INTEGER NOT NULL,

    CONSTRAINT FK_CONTA_BANCARIA FOREIGN KEY (SK_CONTA_BANCARIA) REFERENCES DIM_CONTA_BANCARIA (PK_CONTA_BANCARIA)
   
);


CREATE TABLE IF NOT EXISTS DEPARA_CONTA_FINANCEIRA (
    PK_NORMAL_CONTA_FINANCEIRA SERIAL NOT NULL,
    DS_NORMAL_CONTA_FINANCEIRA VARCHAR(1000) NOT NULL,

    CONSTRAINT PK_NORMAL_CONTA_FINANCEIRA_CONSTRAINT PRIMARY KEY (PK_NORMAL_CONTA_FINANCEIRA)
);

CREATE TABLE IF NOT EXISTS DIM_CONTA_FINANCEIRA (
    PK_CONTA_FINANCEIRA SERIAL NOT NULL,
    CD_CONTA_FINANCEIRA INTEGER,
    -- CD_CONTA_FINANCEIRA INTEGER NOT NULL,
    DS_CONTA_FINANCEIRA VARCHAR(1000) NOT NULL,
    SK_NORMAL_CONTA_FINANCEIRA INTEGER,
    -- SK_NORMAL_CONTA_FINANCEIRA INTEGER NOT NULL,

    CONSTRAINT PK_CONTA_FINANCEIRA_CONSTRAINT PRIMARY KEY (PK_CONTA_FINANCEIRA),
    CONSTRAINT FK_NORMAL_CONTA_FINANCEIRA FOREIGN KEY (SK_NORMAL_CONTA_FINANCEIRA) REFERENCES DEPARA_CONTA_FINANCEIRA (PK_NORMAL_CONTA_FINANCEIRA)
);

CREATE TABLE IF NOT EXISTS FATO_LANCAMENTO (
    SK_UNIDADE INTEGER NOT NULL,
    SK_LANCAMENTO INTEGER NOT NULL,
    PK_LANCAMENTO INTEGER NOT NULL,
    CD_LANCAMENTO INTEGER NOT NULL,
    SK_CONTA_FINANCEIRA INTEGER NOT NULL,
    DT_VENCIMENTO DATE NOT NULL,
    DT_MES_REFERENCIA DATE NOT NULL,
    VL_TOTAL_NF NUMERIC(10,2) NOT NULL,
    DT_VENC_PARCELA DATE NOT NULL,
    SK_FORNECEDOR INTEGER NOT NULL,
    DT_REALIZACAO DATE NOT NULL,
    VL_REALIZACAO NUMERIC(10,2) NOT NULL,
    DS_OBSERVACAO VARCHAR(2000) NOT NULL,
    DT_EMISSAO_NF_DOC DATE NOT NULL,
    DT_INCLUSAO DATE NOT NULL,
    CD_NF_DOC INTEGER NOT NULL,
    SK_CONTA_BANCARIA INTEGER NOT NULL,
    CD_PARCELA INTEGER NOT NULL,
    VL_JURUS NUMERIC(10,2) NOT NULL,
    VL_DESCONTOS NUMERIC(10,2) NOT NULL,
    TP_LANCAMENTO VARCHAR(1) NOT NULL,
    SK_CENTRO_CUSTOS INTEGER NOT NULL,
    TP_FORMA_PGTO VARCHAR(1) NOT NULL,
    CD_DOCUMENTO INTEGER NOT NULL,
    TP_SITUACAO VARCHAR(1) NOT NULL,

    CONSTRAINT FK_UNIDADE FOREIGN KEY (SK_UNIDADE) REFERENCES DIM_UNIDADE (PK_UNIDADE),
    CONSTRAINT FK_CONTA_FINANCEIRA FOREIGN KEY (SK_CONTA_FINANCEIRA) REFERENCES DIM_CONTA_FINANCEIRA (PK_CONTA_FINANCEIRA),
    CONSTRAINT FK_FORNECEDOR FOREIGN KEY (SK_FORNECEDOR) REFERENCES DIM_FORNECEDOR (PK_FORNECEDOR),
    CONSTRAINT FK_CONTA_BANCARIA FOREIGN KEY (SK_CONTA_BANCARIA) REFERENCES DIM_CONTA_BANCARIA (PK_CONTA_BANCARIA),
    CONSTRAINT FK_CENTRO_CUSTOS FOREIGN KEY (SK_CENTRO_CUSTOS) REFERENCES DIM_CENTRO_CUSTOS (PK_CENTRO_CUSTOS)
);

COMMIT;