BEGIN TRANSACTION;

-- Adiciona os dados na tabela DIM_CENTRO_CUSTOS

INSERT INTO DIM_CENTRO_CUSTOS (DS_CENTRO_CUSTOS)
VALUES 
  ('Pronto Atendimento'),
  ('Centro Cirurgico'),
  ('Ambulatorio'),
  ('UI'),
  ('UTI'),
  ('Geral'),
  ('Tecnologia Informacao'),
  ('Farmacia');

-- Adiciona os dados na tabela DIM_CONTA_FINANCEIRA

INSERT INTO DIM_CONTA_FINANCEIRA (DS_CONTA_FINANCEIRA)
VALUES 
  ('SALDO INICIAL'),
  ('TRANSFERÊNCIA ENTRE CONTAS'),
  ('RECEITAS OPERACIONAIS'),
  ('RECEITAS NÃO OPERACIONAIS'),
  ('DEDUÇÕES DE RECEITA'),
  ('IMPOSTOS E CONTRIBUIÇÕES'),
  ('DESPESAS COM PESSOAL'),
  ('OUTRAS DESPESAS COM PESSOAL'),
  ('SERVIÇOS MÉDICOS E ASSISTENCIAIS'),
  ('CONSUMO DE MATERIAL HOSPITALAR E MEDICAMENTOS'),
  ('CONSUMO DE MATERIAIS GERAIS'),
  ('SERVIÇOS TÉCNICOS E OPERACIONAIS'),
  ('SERVIÇOS DE APOIO E LOGÍSTICA'),
  ('MANUTENÇÃO E ASSISTÊNCIA TÉCNICA'),
  ('DESPESAS TECNOLOGIA DA INFORMAÇÃO'),
  ('DESPESAS DE SERVIÇOS NÃO OPERACIONAIS'),
  ('OUTRAS DESPESAS ADMINISTRATIVAS'),
  ('UTILIDADES'),
  ('TAXAS ADMINISTRATIVAS E DE SERVIÇOS DIVERSOS'),
  ('DESPESAS LEGAIS E JUDICIAIS'),
  ('IMPOSTOS E TAXAS'),
  ('SEGUROS'),
  ('DESPESAS FINANCEIRAS/BANCÁRIAS');


COMMIT;